export type BankInfo = { name: string; swift: string };

export const ASIAN_BANKS: Record<string, BankInfo[]> = {
  Singapore: [
    { name: "DBS Bank", swift: "DBSSSGSG" },
    { name: "OCBC Bank", swift: "OCBCSGSG" },
    { name: "UOB Bank", swift: "UOVBSGSG" },
    { name: "Standard Chartered Singapore", swift: "SCBLSGSG" },
    { name: "HSBC Singapore", swift: "HSBCSGSG" },
    { name: "Citibank Singapore", swift: "CITISGSG" },
    { name: "Maybank Singapore", swift: "MBBESGSG" },
  ],
  "Hong Kong": [
    { name: "HSBC Hong Kong", swift: "HSBCHKHH" },
    { name: "Hang Seng Bank", swift: "HASEHKHH" },
    { name: "Bank of China (HK)", swift: "BKCHHKHH" },
    { name: "Standard Chartered HK", swift: "SCBLHKHH" },
    { name: "Citibank Hong Kong", swift: "CITIHKHX" },
    { name: "DBS Hong Kong", swift: "DHBKHKHH" },
    { name: "BEA Bank", swift: "BEASHKHH" },
  ],
  Japan: [
    { name: "MUFG Bank", swift: "BOTKJPJT" },
    { name: "Sumitomo Mitsui (SMBC)", swift: "SMBCJPJT" },
    { name: "Mizuho Bank", swift: "MHCBJPJT" },
    { name: "Nomura Bank", swift: "NRSMJPJT" },
    { name: "Japan Post Bank", swift: "JPPSJPJ1" },
    { name: "Resona Bank", swift: "DIWAJPJT" },
  ],
  "South Korea": [
    { name: "KB Kookmin Bank", swift: "CZNBKRSE" },
    { name: "Shinhan Bank", swift: "SHBKKRSE" },
    { name: "Woori Bank", swift: "HVBKKRSEXXX" },
    { name: "Hana Bank", swift: "HNBNKRSE" },
    { name: "NH Bank", swift: "NACFKRSEXXX" },
    { name: "IBK Bank", swift: "IBKOKRSE" },
  ],
  China: [
    { name: "ICBC", swift: "ICBKCNBJ" },
    { name: "Bank of China", swift: "BKCHCNBJ" },
    { name: "China Construction Bank", swift: "PCBCCNBJ" },
    { name: "Agricultural Bank of China", swift: "ABOCCNBJ" },
    { name: "China Merchants Bank", swift: "CMBCCNBS" },
    { name: "Bank of Communications", swift: "COMMCNSH" },
  ],
  India: [
    { name: "State Bank of India", swift: "SBININBB" },
    { name: "HDFC Bank", swift: "HDFCINBB" },
    { name: "ICICI Bank", swift: "ABORINBB" },
    { name: "Axis Bank", swift: "AXISINBB" },
    { name: "Kotak Mahindra Bank", swift: "ABORINBB" },
    { name: "Yes Bank", swift: "YESBINBB" },
  ],
  Thailand: [
    { name: "Bangkok Bank", swift: "BKKBTHBK" },
    { name: "Kasikornbank", swift: "KASITHBK" },
    { name: "Siam Commercial Bank", swift: "SICOTHBK" },
    { name: "Krungthai Bank", swift: "KRABORSK" },
    { name: "TMBThanachart Bank", swift: "TABORSK" },
  ],
  Malaysia: [
    { name: "Maybank", swift: "MABORSK" },
    { name: "CIMB Bank", swift: "CIBBMYKL" },
    { name: "Public Bank", swift: "PBBEMYKL" },
    { name: "RHB Bank", swift: "RHBBMYKL" },
    { name: "Hong Leong Bank", swift: "HLBBMYKL" },
    { name: "AmBank", swift: "ARBKMYKL" },
  ],
  Indonesia: [
    { name: "BCA (Bank Central Asia)", swift: "CENAIDJA" },
    { name: "Bank Mandiri", swift: "BMRIIDJA" },
    { name: "BNI", swift: "BABORSK" },
    { name: "BRI", swift: "BRINIDJA" },
    { name: "CIMB Niaga", swift: "BNIAIDJA" },
  ],
  Philippines: [
    { name: "BDO Unibank", swift: "ABORSK" },
    { name: "BPI Bank", swift: "BOPIPHMM" },
    { name: "Metrobank", swift: "MBTCPHMM" },
    { name: "UnionBank", swift: "UBPHPHMM" },
    { name: "Security Bank", swift: "SETCPHMM" },
  ],
  Vietnam: [
    { name: "Vietcombank", swift: "BFTVVNVX" },
    { name: "VietinBank", swift: "ICBVVNVX" },
    { name: "BIDV", swift: "BIDVVNVX" },
    { name: "Techcombank", swift: "VTCBVNVX" },
    { name: "MB Bank", swift: "MSCBVNVX" },
  ],
  Taiwan: [
    { name: "CTBC Bank", swift: "CTCBTWTP" },
    { name: "Cathay United Bank", swift: "CATPTWTP" },
    { name: "E.SUN Bank", swift: "ESUNTWTP" },
    { name: "Mega Bank", swift: "ICBCTWTP" },
    { name: "First Bank", swift: "FCBKTWTP" },
  ],
  Australia: [
    { name: "Commonwealth Bank", swift: "CTBAAU2S" },
    { name: "Westpac", swift: "WPACAU2S" },
    { name: "ANZ Bank", swift: "ANZBAU3M" },
    { name: "NAB Bank", swift: "NATAAU33" },
    { name: "Macquarie Bank", swift: "MACQAU2S" },
  ],
  "New Zealand": [
    { name: "ANZ New Zealand", swift: "ANZBNZ22" },
    { name: "Westpac NZ", swift: "WPACNZ2W" },
    { name: "ASB Bank", swift: "ASBBNZ2A" },
    { name: "BNZ Bank", swift: "BKNZNZ22" },
  ],
  "United Arab Emirates": [
    { name: "Emirates NBD", swift: "EABORSK" },
    { name: "First Abu Dhabi Bank", swift: "NBADAEAA" },
    { name: "Abu Dhabi Commercial Bank", swift: "ADCBAEAA" },
    { name: "Dubai Islamic Bank", swift: "DUIBAEADXXX" },
    { name: "Mashreq Bank", swift: "BOMLAEAD" },
  ],
};

export const MARKET_INSTRUMENTS = [
  { symbol: "RFGF", name: "瑞峯 Asia Growth Fund", assetClass: "Equities", price: 48.75, currency: "USD", region: "Asia Pacific", change: 2.4 },
  { symbol: "2800.HK", name: "Tracker Fund HK", assetClass: "ETF", price: 18.92, currency: "HKD", region: "Hong Kong", change: -0.3 },
  { symbol: "1321.T", name: "Nikkei 225 ETF", assetClass: "ETF", price: 38500, currency: "JPY", region: "Japan", change: 1.1 },
  { symbol: "SGS32", name: "SG Gov Bond 2032", assetClass: "Fixed Income", price: 99.45, currency: "SGD", region: "Singapore", change: 0.05 },
  { symbol: "NIFTY50", name: "Nifty 50 India ETF", assetClass: "ETF", price: 2450, currency: "INR", region: "India", change: 0.8 },
  { symbol: "KOSPI", name: "KOSPI 200 ETF", assetClass: "ETF", price: 34200, currency: "KRW", region: "South Korea", change: -0.5 },
  { symbol: "CSI300", name: "CSI 300 China", assetClass: "ETF", price: 4.12, currency: "USD", region: "China", change: 1.5 },
  { symbol: "PC-ASIA", name: "Private Credit Asia", assetClass: "Alternatives", price: 1085.50, currency: "USD", region: "Asia Pacific", change: 0.3 },
  { symbol: "XAU", name: "Gold Bullion", assetClass: "Commodities", price: 2340, currency: "USD", region: "Global", change: 0.7 },
  { symbol: "SG-REIT", name: "SG REIT Index", assetClass: "Real Estate", price: 0.985, currency: "SGD", region: "Singapore", change: -0.2 },
  { symbol: "ASEAN-BD", name: "ASEAN Bond Fund", assetClass: "Fixed Income", price: 102.30, currency: "USD", region: "ASEAN", change: 0.1 },
  { symbol: "JP-DIV", name: "Japan Dividend Fund", assetClass: "Equities", price: 15600, currency: "JPY", region: "Japan", change: 0.9 },
  // New equities
  { symbol: "DBS.SG", name: "DBS Group Holdings", assetClass: "Equities", price: 38.50, currency: "SGD", region: "Singapore", change: 1.2 },
  { symbol: "700.HK", name: "Tencent Holdings", assetClass: "Equities", price: 380.60, currency: "HKD", region: "Hong Kong", change: -1.8 },
  { symbol: "9984.T", name: "SoftBank Group", assetClass: "Equities", price: 8950, currency: "JPY", region: "Japan", change: 3.2 },
  { symbol: "RELIANCE", name: "Reliance Industries", assetClass: "Equities", price: 2890, currency: "INR", region: "India", change: 0.6 },
  { symbol: "005930.KS", name: "Samsung Electronics", assetClass: "Equities", price: 72500, currency: "KRW", region: "South Korea", change: 1.8 },
  { symbol: "BABA", name: "Alibaba Group", assetClass: "Equities", price: 88.20, currency: "USD", region: "China", change: -2.1 },
  { symbol: "9988.HK", name: "Alibaba (HK)", assetClass: "Equities", price: 89.45, currency: "HKD", region: "Hong Kong", change: -1.9 },
  { symbol: "TSMC", name: "Taiwan Semiconductor", assetClass: "Equities", price: 178.50, currency: "USD", region: "Taiwan", change: 2.8 },
  { symbol: "BTC-ETF", name: "Bitcoin ETF Asia", assetClass: "Crypto ETF", price: 62.40, currency: "USD", region: "Global", change: 4.5 },
  { symbol: "ETH-ETF", name: "Ethereum ETF Asia", assetClass: "Crypto ETF", price: 32.10, currency: "USD", region: "Global", change: 3.1 },
  { symbol: "GRAB", name: "Grab Holdings", assetClass: "Equities", price: 3.85, currency: "USD", region: "ASEAN", change: 1.4 },
  { symbol: "SEA", name: "Sea Limited", assetClass: "Equities", price: 72.30, currency: "USD", region: "ASEAN", change: 2.2 },
];

export const HERO_SLIDES = [
  {
    image: "https://images.pexels.com/photos/33847223/pexels-photo-33847223.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=900&w=1600",
    title: "Singapore",
    subtitle: "Global headquarters & wealth hub",
  },
  {
    image: "https://images.pexels.com/photos/33859205/pexels-photo-33859205.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=900&w=1600",
    title: "Hong Kong",
    subtitle: "Capital markets & cross-border desk",
  },
  {
    image: "https://images.pexels.com/photos/9519223/pexels-photo-9519223.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=900&w=1600",
    title: "Tailored for you",
    subtitle: "White-glove private concierge across Asia",
  },
  {
    image: "https://images.pexels.com/photos/9520195/pexels-photo-9520195.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=900&w=1600",
    title: "Lifestyle without limits",
    subtitle: "World Elite cards & Asia privileges",
  },
  {
    image: "https://images.pexels.com/photos/949931/pexels-photo-949931.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=900&w=1600",
    title: "Asia's financial capitals",
    subtitle: "24/7 dealing across 15 markets",
  },
  {
    image: "https://images.pexels.com/photos/881044/pexels-photo-881044.jpeg?auto=compress&cs=tinysrgb&fit=crop&h=900&w=1600",
    title: "Future-forward banking",
    subtitle: "Digital-first, human-centred",
  },
];
