export const CITIES_BY_COUNTRY: Record<string, string[]> = {
  Singapore: ["Singapore"],
  "Hong Kong": ["Central", "Wan Chai", "Tsim Sha Tsui", "Kowloon", "Causeway Bay"],
  Japan: ["Tokyo", "Osaka", "Yokohama", "Nagoya", "Kyoto", "Fukuoka", "Kobe"],
  "South Korea": ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon", "Gwangju"],
  China: ["Shanghai", "Beijing", "Shenzhen", "Guangzhou", "Hangzhou", "Chengdu", "Nanjing"],
  India: ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai", "Kolkata", "Pune"],
  Thailand: ["Bangkok", "Chiang Mai", "Phuket", "Pattaya", "Nonthaburi"],
  Malaysia: ["Kuala Lumpur", "Penang", "Johor Bahru", "Kota Kinabalu", "Ipoh"],
  Indonesia: ["Jakarta", "Surabaya", "Bandung", "Medan", "Bali"],
  Philippines: ["Manila", "Cebu", "Davao", "Quezon City", "Makati"],
  Vietnam: ["Ho Chi Minh City", "Hanoi", "Da Nang", "Haiphong", "Can Tho"],
  Taiwan: ["Taipei", "Kaohsiung", "Taichung", "Tainan", "Hsinchu"],
  Australia: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide"],
  "New Zealand": ["Auckland", "Wellington", "Christchurch", "Hamilton"],
  "United Arab Emirates": ["Dubai", "Abu Dhabi", "Sharjah", "Al Ain"],
};
